name: Build

on: [release]

jobs:
  release-darwin-386:
    runs-on: macOS-latest
    steps: 
    - name: "release darwin/386"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: darwin
        GOARCH: "386"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-darwin-amd64:
    runs-on: macOS-latest
    steps: 
    - name: "release darwin/amd64"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: darwin
        GOARCH: amd64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-linux-386:
    runs-on: ubuntu-latest
    steps: 
    - name: "release linux/386"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: linux
        GOARCH: "386"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps: 
    - name: "release linux/amd64"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: linux
        GOARCH: amd64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows-386:
    runs-on: windows-latest
    steps: 
    - name: "release windows/386"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: windows
        GOARCH: "386"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-windows-amd64:
    runs-on: windows-latest
    steps: 
    - name: "release windows/amd64"
      uses: ngs/go-release.action@v1.0.1
      env:
        GOOS: windows
        GOARCH: amd64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}